version: "3.9"
    
services:
  db:
    image: mysql:8.0.25
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
     - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: loja@123
      MYSQL_DATABASE: loja
      MYSQL_USER: usrloja
      MYSQL_PASSWORD: loja@123

volumes:
  db_data: {}